name: itombs
description: iTombs

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0
  http: ^0.12.2
  toast: 
  image_picker: ^0.6.7+22
  cached_network_image: ^2.0.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  url_launcher: ^6.0.5
  graphql_flutter: ^3.1.0
  flutter_spinkit: ^5.0.0
  page_transition: ^2.0.2
  smooth_page_indicator: ^0.2.3
  provider: ^6.0.0
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^0.1.2
  file_picker: ^2.1.7
  cached_video_player: ^1.0.3
  video_thumbnail:
  flutter_staggered_grid_view: ^0.4.1
  photo_view: ^0.13.0
  swipedetector: ^1.2.0
  webview_flutter:

  

  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.9
  flutter_facebook_login: ^3.0.0
  apple_sign_in: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/graphics/
    - assets/htmls/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
